version: "3"

services:
  database_courses:
    image: postgres
    container_name: devaria_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=devaria
      - POSTGRES_PASSWORD=helloworld123
      - POSTGRES_DB=course
    volumes:
      - pgdata:/data/postgres
      

volumes:
  pgdata:
    driver: local